print("Cotizacion para cada trabajo de mis clientes")
print("--------------------------------------------")
cliente = input("Nombre del cliente:")
print("-----------------------------")
paginas = int(input("¿Cuantas secciones tendra la pagina web?"))
print("-----------------------------------------------------")
botones = int(input("¿Cuantos botones con funciones especiales necesita?"))
print("-----------------------------------------------------------------")
total = (paginas * 1)+(botones * 1)

print("\n--- RESUMEN PARA " + cliente.upper() + " ---")
print("El costo total de tu proyecto es: $" + str(total))
print("Tiempo estimado: " + str(paginas + 1) + " días.")
print("---------------------------------------")